### ISSUE TITLE
Using slots

### ISSUE THREAD

**Issue by mttmccb** [bigopon/aurelia-portal-attribute#1]
Not sure if this works or I've got a stand setup

**I'm submitting a bug report**

* **Framework Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13.1

* **Node Version:**
9.5.0

* **NPM Version:**
5.6.0

* **Browser:**
all

* **Language:**
TypeScript 2.6.2

**Current behavior:**
Portal render slots empty

**Expected/desired behavior:**
Render slot within element with `portal`

**Comment by bigopon** [comment]
`<slot/>` cannot work when placed within a template controller, like `if`, `repeat` or `portal`. Those custom attributes take the responsibility to create the view and do it within their life cycle so their consumers don't know how to project content into them.

You can achieve the composition via `replaceable` / `part`

```html
<!-- my-comp -->
<template>
  <div>Normal element</div>
  <div portal>
    <template replaceable part='slot'></template>
  </div>
</template>
```

Usage:
```html
<!-- app -->
<template>
  <my-comp>
    <template replace-part='slot'>
      <div>item 1</div>
      <div>item 2</div>
      <div>item 3</div>
    <template>
  </my-comp>
</template>
```

**Comment by mttmccb** [comment]
Thanks, I wasn't aware of the workaround, I'll give it a go.

**Comment by mttmccb** [comment]
It did solve the original issue with missing content however I've run into some animation issues and issues using Tether, I suspect I'll need to do some custom animation events.
